# Generated by Django 3.1 on 2020-12-04 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrationmodel',
            old_name='opt',
            new_name='otp',
        ),
    ]
